sudo: false
language: go

go:
  - 1.9
  - "1.10"
  - tip

os:
  - linux
  - osx

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

script:
  - cd cmd/csvnorm && go fmt
  - cd cmd/csvnorm && go build
  - cd cmd/csvnorm && go test -race -v cmd/csvnorm/...
